name: lean-actions
on:
    pull_request:
jobs:
    lint-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - uses: xt0rted/markdownlint-problem-matcher@v3
            - run: npm install
            - run: npm run markdownlint
            - run: npm run textlint
